### ISSUE TITLE
Rename runtime/errors runtime/results

### ISSUE THREAD

**Issue by kuzeko** [kuzeko/graph-databases-testsuite#1]
People get confused by the files `runtime/errors` `runtime/results` as they do not have  extensions,
so we should rename them to `runtime/errors.log` `runtime/results.log`

Moreover, we sometimes use `runtime/errors`  just for debug info, so we should check when this happens and instead use a `runtime/debug.log` file.

**Comment by kuzeko** [comment]
Agreed. 
Not sure if current implementation only prints csv style info there

**Comment by MartinBrugnara** [comment]
The `grep` line in [tp{2,3}/execute.sh](https://github.com/kuzeko/graph-databases-testsuite/blob/master/runtime/tp2/execute.sh#L67)  takes care of it =)

**Comment by kuzeko** [comment]
smart!

**Comment by MartinBrugnara** [comment]
@kuzeko, wrt all the "this goes to debug.log".
Once in query mode we use errors.log for debug see al the `System.err.print(`.

**Comment by kuzeko** [comment]
I see, we can live with that then.
I'll close the issue. We'll reopen if something seems out of place.
